baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My Personal Website'
theme = 'ananke'

[params]
  description = "My personal website with CV and gallery"
  author = "Your Name"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 2

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4
