baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tanner Harms'
theme = 'PaperMod'

[params]
  description = "Personal website - Research, Photography, and More"
  author = "Tanner D. Harms"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/yourusername"

[[params.socialIcons]]
  name = "email"
  url = "mailto:your@email.com"

[[menu.main]]
  name = "About"
  url = "/cv/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Photography"
  url = "/gallery/"
  weight = 3
